function V_der_of_Y = bh_auto_gen_ODEsys(t,Y)
%BH_AUTO_GEN_ODESYS
%    V_DER_OF_Y = BH_AUTO_GEN_ODESYS(T,Y)

%    This function was generated by the Symbolic Math Toolbox version 7.1.
%    22-Jan-2017 18:25:30

t2 = Y(2);
V_der_of_Y = [t2;t2.*-4.0+heaviside(t-5.0).*2.0e2-Y(1).*1.0e2];
