function out1 = Lagrangian_G(k1,k2,theta1_0,theta2_0)
%LAGRANGIAN_G
%    OUT1 = LAGRANGIAN_G(K1,K2,THETA1_0,THETA2_0)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    06-Jun-2018 16:09:55

out1 = [-k1.*theta1_0;-k2.*theta2_0];
