function out1 = M2(I1G_s,I2G_s,L1X_s,L2X_s,TH2_s,m1_s,m2_s)
%M2
%    OUT1 = M2(I1G_S,I2G_S,L1X_S,L2X_S,TH2_S,M1_S,M2_S)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    05-Jun-2018 14:51:29

t2 = L1X_s.^2;
t3 = L2X_s.^2;
t4 = m2_s.*t3.*(1.0./4.0);
t5 = cos(TH2_s);
t6 = L1X_s.*L2X_s.*m2_s.*t5.*(1.0./2.0);
t7 = I2G_s+t4+t6;
out1 = reshape([I1G_s+I2G_s+t4+m1_s.*t2.*(1.0./4.0)+m2_s.*t2+L1X_s.*L2X_s.*m2_s.*t5,t7,t7,I2G_s+t4],[2,2]);
