function out1 = G(k1,k2,theta1_0,theta2_0)
%G
%    OUT1 = G(K1,K2,THETA1_0,THETA2_0)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    05-Jun-2018 14:59:16

out1 = [-k1.*theta1_0;-k2.*theta2_0];
