function out1 = Lagrangian_K(k1,k2)
%LAGRANGIAN_K
%    OUT1 = LAGRANGIAN_K(K1,K2)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    05-Jun-2018 19:06:24

out1 = reshape([k1,0.0,0.0,k2],[2,2]);
