function out1 = Q(b1,b2,tau1,tau2,th1_D,th2_D)
%Q
%    OUT1 = Q(B1,B2,TAU1,TAU2,TH1_D,TH2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    05-Jun-2018 14:59:16

out1 = [tau1+tau2.*2.0-b1.*th1_D-b2.*th2_D.*2.0;tau2-b2.*th2_D];
