function out1 = Lagrangian_Q(b1,b2,tau1,tau2,th1_D,th2_D)
%LAGRANGIAN_Q
%    OUT1 = LAGRANGIAN_Q(B1,B2,TAU1,TAU2,TH1_D,TH2_D)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    05-Jun-2018 19:06:24

out1 = [tau1-b1.*th1_D;tau2-b2.*th2_D];
